# Objetos de Bioconductor para datos de expresion

#### Packages
  + **rnaseqGene Workflow:** este workflow nos permite realizar analisis de expresion diferencial a partir de archivos FASTQ y explorar visualmente los resultados.
  
  + **SummarizedExperiment:** este paquete nos ayuda a almacenar los resultados experimentales de uno o más ensayos, cada uno representado por un objeto similar a una matriz, las filas típicamente representan genomic ranges de interés y las columnas representan las muestras.
  
```
  library(SummarizedExperiment)
  data(airway, package="airway")
  se <- airway
```

```
  se
  
  ## class: RangedSummarizedExperiment 
  ## dim: 64102 8 
  ## metadata(1): ''
  ## assays(1): counts
  ## rownames(64102): ENSG00000000003 ENSG00000000005 ... LRG_98 LRG_99
  ## rowData names(0):
  ## colnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521
  ## colData names(9): SampleName cell ... Sample BioSample
```
  
  + **GenomicRanges:** este paquete nos sirve para representar rangos genómicos, posiciones genómicas y grupos de rangos genómicos.
  
```
  gr <- GRanges(
    seqnames = Rle(c("chr1", "chr2", "chr1", "chr3"), c(1, 3, 2, 4)),
    ranges = IRanges(101:110, end = 111:120, names = head(letters, 10)),
    strand = Rle(strand(c("-", "+", "*", "+", "-")), c(1, 2, 2, 3, 2)),
    score = 1:10,
    GC = seq(1, 0, length=10))
```
  
```
  gr
  
  ## GRanges object with 10 ranges and 2 metadata columns:
  ##     seqnames    ranges strand |     score        GC
  ##        <Rle> <IRanges>  <Rle> | <integer> <numeric>
  ##   a     chr1   101-111      - |         1  1.000000
  ##   b     chr2   102-112      + |         2  0.888889
  ##   c     chr2   103-113      + |         3  0.777778
  ##   d     chr2   104-114      * |         4  0.666667
  ##   e     chr1   105-115      * |         5  0.555556
  ##   f     chr1   106-116      + |         6  0.444444
  ##   g     chr3   107-117      + |         7  0.333333
  ##   h     chr3   108-118      + |         8  0.222222
  ##   i     chr3   109-119      - |         9  0.111111
  ##   j     chr3   110-120      - |        10  0.000000
  ##   -------
  ##   seqinfo: 3 sequences from an unspecified genome; no seqlengths
```
  
  + **rtracklayer:** este paquete nos permite interactuar con múltiples genome browsers y manipular los annotation tracks en varios formatos



```
  ## Lets build our first SummarizedExperiment object
  library("SummarizedExperiment")
  ## ?SummarizedExperiment
  
  ## De los ejemplos en la ayuda oficial
  
  ## Creamos los datos para nuestro objeto de tipo SummarizedExperiment
  ## para 200 genes a lo largo de 6 muestras
  nrows <- 200
  ncols <- 6
  ## Números al azar de cuentas
  set.seed(20210223)
  counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
  ## Información de nuestros genes
  rowRanges <- GRanges(
    rep(c("chr1", "chr2"), c(50, 150)),
    IRanges(floor(runif(200, 1e5, 1e6)), width = 100),
    strand = sample(c("+", "-"), 200, TRUE),
    feature_id = sprintf("ID%03d", 1:200)
  )
  names(rowRanges) <- paste0("gene_", seq_len(length(rowRanges)))
  ## Información de nuestras muestras
  colData <- DataFrame(
    Treatment = rep(c("ChIP", "Input"), 3),
    row.names = LETTERS[1:6]
  )
  ## Juntamos ahora toda la información en un solo objeto de R
  rse <- SummarizedExperiment(
    assays = SimpleList(counts = counts),
    rowRanges = rowRanges,
    colData = colData
  )
  
  ## Exploremos el objeto resultante
  rse


  ## class: RangedSummarizedExperiment 
  ## dim: 200 6 
  ## metadata(0):
  ## assays(1): counts
  ## rownames(200): gene_1 gene_2 ... gene_199 gene_200
  ## rowData names(1): feature_id
  ## colnames(6): A B ... E F
  ## colData names(1): Treatment
```

```
  ## Número de genes y muestras
  dim(rse)

  ## [1] 200   6
  
  
  ## IDs de nuestros genes y muestras
  dimnames(rse)
  
  
  ## Nombres de tablas de cuentas que tenemos (RPKM, CPM, counts,   logcounts, etc)
  assayNames(rse)
  
  
  ## Información de los genes en un objeto de Bioconductor
  rowRanges(rse)      ·Regresa un GRanges·
  
  
  ## Tabla con información de los genes
  rowData(rse) # es idéntico a 'mcols(rowRanges(rse))'
  
  
  ## Tabla con información de las muestras
  colData(rse)
```



### Ejercicio
  Explica que sucede en las siguientes líneas de comando
  
```
  rse[1:2, ]
  
  ## class: RangedSummarizedExperiment 
  ## dim: 2 6 
  ## metadata(0):
  ## assays(1): counts
  ## rownames(2): gene_1 gene_2
  ## rowData names(1): feature_id
  ## colnames(6): A B ... E F
  ## colData names(1): Treatment
```
  + aqui estamos accediendo unicamente a los primeros dos genes (dos filas)
  

```
  rse[, c("A", "D", "F")]
  
  ## class: RangedSummarizedExperiment 
  ## dim: 200 3 
  ## metadata(0):
  ## assays(1): counts
  ## rownames(200): gene_1 gene_2 ... gene_199 gene_200
  ## rowData names(1): feature_id
  ## colnames(3): A D F
  ## colData names(1): Treatment
```
  + aqui estamos accediendo unicamente a tres columnas de seis, en este caso A, D y F (tres muestras)
  

  
### iSEE
  + **iSEE** es un paquete que crea una interfaz gráfica interactiva que permite explorar los datos almacenados en objetos __SummarizedExperiment__
  
  Para explorar el objeto rse de forma interactiva
  
```
  ## Explora el objeto rse de forma interactiva
  library("iSEE")
  iSEE::iSEE(rse)
```
  
  
  
### Ejercicio con spatialLIBD
  + **SingleCellExperiment** (package) es un objeto muy similar a SummarizedExperiment, que en este caso almacena datos de experimentos single-cell
  
  Para descargar datos de un objeto SingleCellExperiment haremos lo siguiente
  
```
  ## Descarguemos unos datos de spatialLIBD
  sce_layer <- spatialLIBD::fetch_data("sce_layer")
  
  sce_layer
  
  ## class: SingleCellExperiment 
  ## dim: 22331 76 
  ## metadata(0):
  ## assays(2): counts logcounts
  ## rownames(22331): ENSG00000243485 ENSG00000238009 ...   ENSG00000278384 ENSG00000271254
  ## rowData names(10): source type ... is_top_hvg is_top_hvg_sce_layer
  ## colnames(76): 151507_Layer1 151507_Layer2 ... 151676_Layer6   151676_WM
  ## colData names(13): sample_name layer_guess ...   layer_guess_reordered_short spatialLIBD
  ## reducedDimNames(6): PCA TSNE_perplexity5 ... UMAP_neighbors15   PCAsub
  ## mainExpName: NULL
  ## altExpNames(0)
  
  ## Revisemos el tamaño de este objeto
  lobstr::obj_size(sce_layer) / 1024^2 ## Convertir a MB
  
  ## Exploramos los datos con iSEE
  iSEE::iSEE(sce_layer)
```
  
##### Preguntas
  + ¿Entre los genes MOBP, MBP y PCP4 cuales tienen una expresion similar?
  
  de entre estos tres genes aquellos que presentan un patrón de expresión similar son MBP y MOBP
  
  + ¿En que capas se expresan más los genes MOBP y MBP?
  
  Ambos genes se ven más expresandos en la capa WM
  
# Datos de RNA-seq a través de recount3

 + **recount3** es un paquete que habilita el acceso a una gran cantidad de información de datos de RNA-seq uniformemente procesados de humano y ratón, se pueden descargar objetos  RangedSummarizedExperiment al nivel de gen, exón o exon-exon junctions. 
 Este paquete ayuda a que todos podamos analizar los datos sin importar quien tiene acceso a high performance computing.
 
### Usar recount3
  Una vez descargado el paquete debemos identificar un estudio de interés y determinar el nivel al que queremos accesar a la información (gen, exòn, etc.), ahora que definimos el estudio de interés descargamos los datos usando la función **create_rse()** (podemos incluso especificar la anotación que queremos en los argumentos).
  
```
  ## Revisemos todos los proyectos con datos de humano en recount3
  human_projects <- available_projects()
  
  ## Encuentra tu proyecto de interés. Aquí usaremos
  ## SRP009615 de ejemplo
  proj_info <- subset(
      human_projects,
      project == "SRP009615" & project_type == "data_sources"
  )
  
  ## Crea un objeto de tipo RangedSummarizedExperiment (RSE)
  ## con la información a nivel de genes
  rse_gene_SRP009615 <- create_rse(proj_info)
  
  ## Explora el objeto RSE
  rse_gene_SRP009615
```

```
  ## class: RangedSummarizedExperiment 
    ## dim: 63856 12 
    ## metadata(8): time_created recount3_version ... annotation     recount3_url
    ## assays(1): raw_counts
    ## rownames(63856): ENSG00000278704.1 ENSG00000277400.1 ...     ENSG00000182484.15_PAR_Y ENSG00000227159.8_PAR_Y
    ## rowData names(10): source type ... havana_gene tag
    ## colnames(12): SRR387777 SRR387778 ... SRR389077 SRR389078
    ## colData names(175): rail_id external_id ...     recount_pred.curated.cell_line BigWigURL
```

  Para explorar los proyectos de forma interactiva

```
  ## Explora los proyectos disponibles de forma interactiva
  proj_info_interactive <-   interactiveDisplayBase::display(human_projects)
  ## Selecciona un solo renglón en la tabla y da click en "send".
  
  ## Aquí verificamos que solo seleccionaste un solo renglón.
  stopifnot(nrow(proj_info_interactive) == 1)
  
  ## Crea el objeto RSE
  rse_gene_interactive <- create_rse(proj_info_interactive)
```

  Una vez que tenemos las cuentas podemos utilizar **transform_counts()** o **compute_read_counts()** para de esta manera convertir en los formatos esperados por otras herramientas
  
```
    ## Convirtamos las cuentas por nucleotido a cuentas por lectura
    ## usando compute_read_counts().
    ## Para otras transformaciones como RPKM y TPM, revisa     transform_counts().
    assay(rse_gene_SRP009615, "counts") <-     compute_read_counts(rse_gene_SRP009615)
    
    ## Para este estudio en específico, hagamos más fácil de usar la
  ## información del experimento
  rse_gene_SRP009615 <- expand_sra_attributes(rse_gene_SRP009615)
  colData(rse_gene_SRP009615)[
      ,
      grepl("^sra_attribute", colnames(colData(rse_gene_SRP009615)))
  ]
```

### Ejercicio
  
  * Imagen en el repositorio *
  





